//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixAddress
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_HouseSeriesAddrList
    {
        public int lngHouseSeriesAddrListID { get; set; }
        public Nullable<int> lngHouseSeriesID { get; set; }
        public Nullable<int> lngKladdrID { get; set; }
        public string strAddr { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    }
}
